### ISSUE TITLE
Boto3 describe_stack_resources doesn't take TemplateStage as parameter

### ISSUE THREAD

**Issue by hown3d** [iann0036/cfn-stack-rename#3]
Hey, thanks for your work!

I tried running your script and have encountered the following error:

```
Traceback (most recent call last):
  File "/Users/.../workspace/foss/cfn-stack-rename/index.py", line 1352, in <module>
    original_resources = cfnclient.describe_stack_resources(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 337, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 628, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 676, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/usr/local/lib/python3.9/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "TemplateStage", must be one of: StackName, LogicalResourceId, PhysicalResourceId
```

I removed TemplateStage as argument and it worked. I'll provide a pull request as described.

Regards

**Comment by iann0036** [comment]
Thanks!

Looks like a leftover from a previous fix.
